language: objective-c
matrix:
  include:
    - osx_image: xcode7.3
      env: DEVICE="iPad 2" VERSION=9.0
    - osx_image: xcode7.3
      env: DEVICE="iPad 2" VERSION=9.3
before_install:
- export LANG=en_US.UTF-8
before_script:
- gem install cocoapods
- ( cd ~/.cocoapods/repos/master && git fetch && git reset --hard origin/master )
- pod install --project-directory=Example
script:
- xctool -sdk iphonesimulator -workspace Example/RegexNamedCaptureGroups.xcworkspace -scheme RegexNamedCaptureGroups-Example -destination "platform=iOS Simulator,name=$DEVICE,OS=$VERSION" clean test
- pod lib lint --allow-warnings
